# -*- coding: utf-8 -*-
"""Dashboars_Streamlit_7(new 2hr ahead data).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V8w4gNyaGTuMOcN5evaqVnrYESrYznVu
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from datetime import time
from textwrap import dedent

st.set_page_config(
    page_title="Solar GHI Forecasting Dashboard",
    layout="wide"
)

st.markdown(
    "<h1 style='text-align: center;'>☀️ Solar GHI Forecasting Dashboard</h1>",
    unsafe_allow_html=True
)

DATA_PATH = "Bias Correction_with_Day_Ahead_2hrahead_Forecast_3.csv"

@st.cache_data
def load_data():
    df = pd.read_csv(DATA_PATH)

    df["valid_time_ist"] = (
        pd.to_datetime(df["valid_time_ist"])
          .dt.tz_localize(None)
    )
    df["valid_time_ist"] = pd.to_datetime(df["valid_time_ist"])

    df = df.rename(columns={
        "avg_ghi": "GFS_GHI",
        "ALLSKY_SFC_SW_DWN": "Actual_GHI",
        "Day_Ahead_Forecast": "Daily_Forecast_GHI",
        "2hr_ahead_forecast": "Two_Hour_Ahead_Forecast"
    })

    df = df.sort_values("valid_time_ist").reset_index(drop=True)
    return df

df = load_data()

st.subheader("🏭 Plant & Forecast Configuration")

available_dates = sorted(df["valid_time_ist"].dt.date.unique())

c1, c2, c3, c4 = st.columns([1, 1.5, 1, 1])

with c1:
    state = st.selectbox(
        "State",
        ["Karnataka"]
    )

with c2:
    plant = st.selectbox(
        "Plant Name",
        ["Pavagada Solar Plant"]
    )

with c3:
    selected_date = st.date_input(
        "Date",
        value=available_dates[-1],
        min_value=available_dates[0],
        max_value=available_dates[-1]
    )

with c4:
    time_options = pd.date_range("06:30", "17:30", freq="1h").time

    selected_time = st.selectbox(
        "Time",
        options=time_options,
        format_func=lambda t: t.strftime("%H:%M")
    )


day_df = df[df["valid_time_ist"].dt.date == selected_date].copy()

day_df["hour"] = (
    day_df["valid_time_ist"].dt.hour +
    day_df["valid_time_ist"].dt.minute / 60
)

day_df = day_df[
    (day_df["hour"] >= 6.5) &
    (day_df["hour"] <= 17.5)
].copy()

selected_datetime = pd.to_datetime(
    str(selected_date) + " " + selected_time.strftime("%H:%M")
)

two_hour_end_time = selected_datetime + pd.Timedelta(hours=2)

target_row = day_df[
    day_df["valid_time_ist"] == two_hour_end_time
]

has_two_hour_forecast = (
    not target_row.empty and
    pd.notna(target_row["Two_Hour_Ahead_Forecast"].iloc[0])
)

if has_two_hour_forecast:
    two_hour_df = day_df[
        day_df["valid_time_ist"] <= two_hour_end_time
    ].copy()

    two_hour_df = two_hour_df.dropna(
        subset=["Two_Hour_Ahead_Forecast"]
    )
else:
    two_hour_df = pd.DataFrame()


if day_df.empty:
    st.stop()

else:

    left_col, right_col = st.columns(2)

    ymax = max(
        day_df["Actual_GHI"].max(),
        day_df["GFS_GHI"].max(),
        day_df["Daily_Forecast_GHI"].max()
    )

    ymax = (int(ymax / 100) + 1) * 100

    tick_times = day_df["valid_time_ist"].dt.strftime("%H:%M").tolist()

    # ============================
    # Dashboard Colors
    # ============================
    GFS_COLOR = "#76B7F2"             # Light blue
    DAILY_FORECAST_COLOR = "#F28E2B"  # Orange
    DAILY_FORECAST_FILL = "rgba(242,142,43,0.25)"
    TWO_HOUR_COLOR = "#2CA02C"        # Green
    ACTUAL_COLOR = "#636EFA"          # Blue

    # =====================================================
    # FIRST ROW: DAILY FORECAST GHI ONLY
    # =====================================================

    fig1 = go.Figure()

    fig1.add_trace(go.Scatter(
        x=day_df["valid_time_ist"],
        y=day_df["Daily_Forecast_GHI"],
        mode="lines+markers",
        name="Daily Forecast GHI",
        line=dict(color=DAILY_FORECAST_COLOR, width=2),
        marker=dict(color=DAILY_FORECAST_COLOR),
         fill="tozeroy",
        fillcolor=DAILY_FORECAST_FILL
    ))

    if has_two_hour_forecast:

        fig1.add_trace(go.Scatter(
            x=two_hour_df["valid_time_ist"],
            y=two_hour_df["Two_Hour_Ahead_Forecast"],
            mode="lines+markers",
            name="2-Hour Ahead Forecast",
            line=dict(color=TWO_HOUR_COLOR),
            marker=dict(color=TWO_HOUR_COLOR)
        ))

    else:
        pass

    fig1.update_layout(
        title=dict(
            text=f"Forecasted GHI for {selected_date}",
            font=dict(size=24)
        ),
        xaxis_title="Time",
        yaxis_title="GHI",
        height=450,
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1
        )
    )

    fig1.update_xaxes(
        tickmode="array",
        tickvals=day_df["valid_time_ist"],
        ticktext=tick_times
    )

    fig1.update_yaxes(range=[0, ymax])

    row1_col, row1_space = st.columns([4.5, 0.8])

    with row1_col:
        st.plotly_chart(fig1, use_container_width=True, key="daily_forecast_main")

    with row1_space:

        with st.container(border=True):

            st.markdown("### 📥 Export Forecast Data")

            download_cols = [
                "valid_time_ist",
                "Actual_GHI",
                "GFS_GHI",
                "Daily_Forecast_GHI",
                "Two_Hour_Ahead_Forecast"
            ]

            rename_download_cols = {
                "valid_time_ist": "Time",
                "Actual_GHI": "Actual GHI",
                "GFS_GHI": "GFS GHI",
                "Daily_Forecast_GHI": "Day Ahead Forecast GHI",
                "Two_Hour_Ahead_Forecast": "2-Hour Ahead Forecast GHI"
            }

            # =====================================================
            # DOWNLOAD 1: START OF DATA TO SELECTED DATE
            # =====================================================

            cumulative_download_df = df[
                df["valid_time_ist"].dt.date <= selected_date
            ].copy()

            cumulative_download_df["hour"] = (
                cumulative_download_df["valid_time_ist"].dt.hour
                + cumulative_download_df["valid_time_ist"].dt.minute / 60
            )

            cumulative_download_df = cumulative_download_df[
                (cumulative_download_df["hour"] >= 6.5)
                & (cumulative_download_df["hour"] <= 17.5)
            ].copy()

            cumulative_download_df = cumulative_download_df[
                download_cols
            ].rename(columns=rename_download_cols)

            cumulative_csv = cumulative_download_df.to_csv(
                index=False
            ).encode("utf-8")


            st.download_button(
                label="⬇️ Download data through selected date",
                data=cumulative_csv,
                file_name=f"forecast_data_through_{selected_date}.csv",
                mime="text/csv",
                use_container_width=True,
                key="download_cumulative_forecast"
            )


            # =====================================================
            # DOWNLOAD 2: SELECTED DATE ONLY
            # =====================================================

            day_download_df = day_df[
                download_cols
            ].copy().rename(columns=rename_download_cols)

            day_csv = day_download_df.to_csv(
                index=False
            ).encode("utf-8")

            st.download_button(
                label="⬇️ Download selected day data",
                data=day_csv,
                file_name=f"forecast_data_{selected_date}.csv",
                mime="text/csv",
                use_container_width=True,
                key="download_selected_day_forecast"
            )

    # =====================================================
    # SECOND ROW: TWO PLOTS
    # LEFT: GFS VS DAILY FORECAST
    # RIGHT: DAILY FORECAST GHI ONLY
    # =====================================================

    left_col, right_col = st.columns(2)

    left_col, right_col = st.columns(2)

    with left_col:

        with st.container(border=True):

            st.markdown("### GFS vs Daily Forecast GHI")

            fig2 = go.Figure()

            fig2.add_trace(go.Scatter(
                x=day_df["valid_time_ist"],
                y=day_df["GFS_GHI"],
                mode="lines+markers",
                name="GFS GHI",
                line=dict(color=GFS_COLOR),
                marker=dict(color=GFS_COLOR)
            ))

            fig2.add_trace(go.Scatter(
                x=day_df["valid_time_ist"],
                y=day_df["Daily_Forecast_GHI"],
                mode="lines+markers",
                name="Daily Forecast GHI",
                line=dict(color=DAILY_FORECAST_COLOR),
                marker=dict(color=DAILY_FORECAST_COLOR)

            ))

            fig2.update_layout(
                xaxis_title="Time",
                yaxis_title="GHI",
                height=430,
                margin=dict(l=20, r=20, t=45, b=20),
                legend=dict(
                    orientation="h",
                    yanchor="bottom",
                    y=1.02,
                    xanchor="right",
                    x=1
                )
            )

            fig2.update_xaxes(
                tickmode="array",
                tickvals=day_df["valid_time_ist"],
                ticktext=tick_times
            )

            fig2.update_yaxes(range=[0, ymax])

            st.plotly_chart(
                fig2,
                use_container_width=True,
                key="gfs_vs_daily_forecast"
            )


    with right_col:
        with st.container(border=True):
            st.markdown("### GFS vs 2-Hour Ahead Forecast")

            fig3 = go.Figure()

            if has_two_hour_forecast:
                fig3.add_trace(go.Scatter(
                    x=two_hour_df["valid_time_ist"],
                    y=two_hour_df["GFS_GHI"],
                    mode="lines+markers",
                    name="GFS GHI",
                    line=dict(color=GFS_COLOR),
                    marker=dict(color=GFS_COLOR)
                ))

                fig3.add_trace(go.Scatter(
                    x=two_hour_df["valid_time_ist"],
                    y=two_hour_df["Two_Hour_Ahead_Forecast"],
                    mode="lines+markers",
                    name="2-Hour Ahead Forecast",
                    line=dict(color=TWO_HOUR_COLOR),
                    marker=dict(color=TWO_HOUR_COLOR)
                ))

                fig3_tick_vals = two_hour_df["valid_time_ist"]
                fig3_tick_times = (
                    two_hour_df["valid_time_ist"]
                    .dt.strftime("%H:%M")
                    .tolist()
                )

            else:
                selected_target_time = two_hour_end_time.strftime("%H:%M")

                st.warning(
                    f"No 2-hour ahead forecast available on {selected_date} "
                    f"for selected time {selected_time.strftime('%H:%M')} "
                    f"(target time: {selected_target_time})"
                )

                fig3_tick_vals = day_df["valid_time_ist"]
                fig3_tick_times = (
                    day_df["valid_time_ist"]
                    .dt.strftime("%H:%M")
                    .tolist()
                )

            fig3.update_layout(
                xaxis_title="Time",
                yaxis_title="GHI",
                height=430,
                margin=dict(l=20, r=20, t=45, b=20),
                legend=dict(
                    orientation="h",
                    yanchor="bottom",
                    y=1.02,
                    xanchor="right",
                    x=1
                )
            )

            fig3.update_xaxes(
                tickmode="array",
                tickvals=fig3_tick_vals,
                ticktext=fig3_tick_times
            )

            fig3.update_yaxes(range=[0, ymax])

            st.plotly_chart(
                fig3,
                use_container_width=True,
                key="two_hour_gfs_comparison"
            )

    # =====================================================
    # PREVIOUS DAY COMPARISON PLOTS
    # =====================================================

    selected_date_only = pd.to_datetime(selected_date).date()
    previous_day = selected_date_only - pd.Timedelta(days=1)

    previous_df = df[
        df["valid_time_ist"].dt.date == previous_day
    ].copy()

    previous_df["hour"] = (
        previous_df["valid_time_ist"].dt.hour
        + previous_df["valid_time_ist"].dt.minute / 60
    )

    previous_df = previous_df[
        (previous_df["hour"] >= 6.5)
        & (previous_df["hour"] <= 17.5)
    ].copy()

    if previous_df.empty:
        st.warning(
            f"No previous-day data available for {previous_day}."
        )

    else:
        st.markdown(
            f"""
            <h2 style="margin-top:20px; margin-bottom:10px;">
                📈 Previous Day Performance Comparison ({previous_day})
            </h2>
            """,
            unsafe_allow_html=True
        )

        # Common y-axis maximum
        prev_ymax = max(
            previous_df["Actual_GHI"].max(),
            previous_df["GFS_GHI"].max(),
            previous_df["Daily_Forecast_GHI"].max(),
            previous_df["Two_Hour_Ahead_Forecast"].max(skipna=True)
        )

        prev_ymax = (int(prev_ymax / 100) + 1) * 100

        prev_tick_times = (
            previous_df["valid_time_ist"]
            .dt.strftime("%H:%M")
            .tolist()
        )

        prev_left, prev_right = st.columns(2)

        # =====================================================
        # PREVIOUS DAY LEFT PLOT
        # Actual + GFS + Daily Forecast
        # =====================================================

        with prev_left:
            with st.container(border=True):

                st.markdown(
                    "### Actual vs GFS vs Daily Forecast"
                )

                fig_prev1 = go.Figure()

                # Actual GHI — green dotted
                fig_prev1.add_trace(go.Scatter(
                    x=previous_df["valid_time_ist"],
                    y=previous_df["Actual_GHI"],
                    mode="lines+markers",
                    name="Actual GHI",
                    line=dict(color=ACTUAL_COLOR, dash="dot"),
                    marker=dict(color=ACTUAL_COLOR)
                ))

                # GFS GHI — blue
                fig_prev1.add_trace(go.Scatter(
                    x=previous_df["valid_time_ist"],
                    y=previous_df["GFS_GHI"],
                    mode="lines+markers",
                    name="GFS GHI",
                    line=dict(color=GFS_COLOR),
                    marker=dict(color=GFS_COLOR)
                ))

                # Daily Forecast — orange
                fig_prev1.add_trace(go.Scatter(
                    x=previous_df["valid_time_ist"],
                    y=previous_df["Daily_Forecast_GHI"],
                    mode="lines+markers",
                    name="Daily Forecast GHI",
                    line=dict(color=DAILY_FORECAST_COLOR),
                    marker=dict(color=DAILY_FORECAST_COLOR)
                ))

                fig_prev1.update_layout(
                    xaxis_title="Time",
                    yaxis_title="GHI",
                    height=430,
                    margin=dict(
                        l=20,
                        r=20,
                        t=45,
                        b=20
                    ),
                    legend=dict(
                        orientation="h",
                        yanchor="bottom",
                        y=1.02,
                        xanchor="right",
                        x=1
                    )
                )

                fig_prev1.update_xaxes(
                    tickmode="array",
                    tickvals=previous_df["valid_time_ist"],
                    ticktext=prev_tick_times
                )

                fig_prev1.update_yaxes(
                    range=[0, prev_ymax]
                )

                st.plotly_chart(
                    fig_prev1,
                    use_container_width=True,
                    key="previous_day_actual_gfs_forecast"
                )

        # =====================================================
        # PREVIOUS DAY RIGHT PLOT
        # Actual + GFS + 2-Hour Ahead
        # =====================================================

        with prev_right:
            with st.container(border=True):

                st.markdown(
                    "### Actual vs GFS vs 2-Hour Ahead Forecast"
                )

                fig_prev2 = go.Figure()

                # Since the previous day is complete, use all rows
                # where 2-hour-ahead forecast exists.
                previous_two_hour_df = previous_df.dropna(
                    subset=["Two_Hour_Ahead_Forecast"]
                ).copy()

                if not previous_two_hour_df.empty:

                    # Actual GHI — green dotted
                    fig_prev2.add_trace(go.Scatter(
                        x=previous_two_hour_df["valid_time_ist"],
                        y=previous_two_hour_df["Actual_GHI"],
                        mode="lines+markers",
                        name="Actual GHI",
                        line=dict(color=ACTUAL_COLOR, dash="dot"),
                        marker=dict(color=ACTUAL_COLOR)
                    ))

                    # GFS GHI — blue
                    fig_prev2.add_trace(go.Scatter(
                        x=previous_two_hour_df["valid_time_ist"],
                        y=previous_two_hour_df["GFS_GHI"],
                        mode="lines+markers",
                        name="GFS GHI",
                        line=dict(color=GFS_COLOR),
                        marker=dict(color=GFS_COLOR)
                    ))

                    # 2-Hour Ahead Forecast — red
                    fig_prev2.add_trace(go.Scatter(
                        x=previous_two_hour_df["valid_time_ist"],
                        y=previous_two_hour_df[
                            "Two_Hour_Ahead_Forecast"
                        ],
                        mode="lines+markers",
                        name="2-Hour Ahead Forecast",
                        line=dict(color=TWO_HOUR_COLOR),
                        marker=dict(color=TWO_HOUR_COLOR)

                    ))

                    prev2_tick_vals = (
                        previous_two_hour_df["valid_time_ist"]
                    )

                    prev2_tick_text = (
                        previous_two_hour_df["valid_time_ist"]
                        .dt.strftime("%H:%M")
                        .tolist()
                    )

                else:
                    st.warning(
                        f"No previous-day 2-hour ahead forecast "
                        f"data available for {previous_day}."
                    )

                    prev2_tick_vals = previous_df["valid_time_ist"]

                    prev2_tick_text = (
                        previous_df["valid_time_ist"]
                        .dt.strftime("%H:%M")
                        .tolist()
                    )

                fig_prev2.update_layout(
                    xaxis_title="Time",
                    yaxis_title="GHI",
                    height=430,
                    margin=dict(
                        l=20,
                        r=20,
                        t=45,
                        b=20
                    ),
                    legend=dict(
                        orientation="h",
                        yanchor="bottom",
                        y=1.02,
                        xanchor="right",
                        x=1
                    )
                )

                fig_prev2.update_xaxes(
                    tickmode="array",
                    tickvals=prev2_tick_vals,
                    ticktext=prev2_tick_text
                )

                fig_prev2.update_yaxes(
                    range=[0, prev_ymax]
                )

                st.plotly_chart(
                    fig_prev2,
                    use_container_width=True,
                    key="previous_day_two_hour_actual_gfs"
                )
    # =====================================================
    # CUMULATIVE ERROR METRICS: START DATE TO PREVIOUS DAY
    # =====================================================

    selected_date_only = pd.to_datetime(selected_date).date()
    previous_day = selected_date_only - pd.Timedelta(days=1)

    eval_df = df[
        df["valid_time_ist"].dt.date <= previous_day
    ].copy()

    eval_df = eval_df.dropna(
        subset=["Actual_GHI", "GFS_GHI", "Daily_Forecast_GHI"]
    )

    eval_df["hour"] = (
        eval_df["valid_time_ist"].dt.hour +
        eval_df["valid_time_ist"].dt.minute / 60
    )

    eval_df = eval_df[
        (eval_df["hour"] >= 6.5) &
        (eval_df["hour"] <= 17.5) &
        (eval_df["Actual_GHI"] > 50)
    ].copy()

    if not eval_df.empty:

        start_date = eval_df["valid_time_ist"].dt.date.min()
        end_date = eval_df["valid_time_ist"].dt.date.max()

        actual = eval_df["Actual_GHI"]
        before = eval_df["GFS_GHI"]
        after = eval_df["Daily_Forecast_GHI"]

        mae_before = (actual - before).abs().mean()
        mae_after = (actual - after).abs().mean()

        rmse_before = np.sqrt(((actual - before) ** 2).mean())
        rmse_after = np.sqrt(((actual - after) ** 2).mean())

        mape_before = ((actual - before).abs() / actual).mean() * 100
        mape_after = ((actual - after).abs() / actual).mean() * 100

        st.markdown(
            f"### 📊 Cumulative Performance of  Daily Forecast "
            f"({start_date} to {end_date})"
        )

        metric_col1, metric_col2, metric_col3 = st.columns(3)

        # ---------------- MAPE ----------------
        with metric_col1:
            fig_mape = go.Figure()

            fig_mape.add_trace(go.Bar(
                x=["Before", "After"],
                y=[mape_before, mape_after],
                text=[round(mape_before, 2), round(mape_after, 2)],
                textposition="auto",
                marker_color=[GFS_COLOR, DAILY_FORECAST_COLOR]
            ))

            fig_mape.update_layout(
                title="MAPE",
                xaxis_title="Model",
                yaxis_title="MAPE (%)",
                height=350
            )

            st.plotly_chart(
                fig_mape,
                use_container_width=True,
                key="mape_cumulative_chart"
            )

        # ---------------- MAE ----------------
        with metric_col2:
            fig_mae = go.Figure()

            fig_mae.add_trace(go.Bar(
                x=["Before", "After"],
                y=[mae_before, mae_after],
                text=[round(mae_before, 2), round(mae_after, 2)],
                textposition="auto",
                marker_color=[GFS_COLOR, DAILY_FORECAST_COLOR]
            ))

            fig_mae.update_layout(
                title="MAE",
                xaxis_title="Model",
                yaxis_title="MAE",
                height=350
            )

            st.plotly_chart(
                fig_mae,
                use_container_width=True,
                key="mae_cumulative_chart"
            )

        # ---------------- RMSE ----------------
        with metric_col3:
            fig_rmse = go.Figure()

            fig_rmse.add_trace(go.Bar(
                x=["Before", "After"],
                y=[rmse_before, rmse_after],
                text=[round(rmse_before, 2), round(rmse_after, 2)],
                textposition="auto",
                marker_color=[GFS_COLOR, DAILY_FORECAST_COLOR]
            ))

            fig_rmse.update_layout(
                title="RMSE",
                xaxis_title="Model",
                yaxis_title="RMSE",
                height=350
            )

            st.plotly_chart(
                fig_rmse,
                use_container_width=True,
                key="rmse_cumulative_chart"
            )

    else:
        st.warning(
            "Not enough valid previous-day data to calculate cumulative forecast performance."
        )

    # =====================================================
    # CUMULATIVE 2-HOUR-AHEAD FORECAST PERFORMANCE
    # Start of data through previous day
    # =====================================================

    cumulative_2hr_df = df[
        df["valid_time_ist"].dt.date <= previous_day
    ].copy()

    cumulative_2hr_df["hour"] = (
        cumulative_2hr_df["valid_time_ist"].dt.hour
        + cumulative_2hr_df["valid_time_ist"].dt.minute / 60
    )

    # Use only rows where all required values are available
    cumulative_2hr_df = cumulative_2hr_df.dropna(
        subset=[
            "Actual_GHI",
            "GFS_GHI",
            "Daily_Forecast_GHI",
            "Two_Hour_Ahead_Forecast"
        ]
    ).copy()

    cumulative_2hr_df = cumulative_2hr_df[
        (cumulative_2hr_df["hour"] >= 6.5)
        & (cumulative_2hr_df["hour"] <= 17.5)
        & (cumulative_2hr_df["Actual_GHI"] > 50)
    ].copy()

    if not cumulative_2hr_df.empty:

        cumulative_2hr_start = (
            cumulative_2hr_df["valid_time_ist"]
            .dt.date
            .min()
        )

        cumulative_2hr_end = (
            cumulative_2hr_df["valid_time_ist"]
            .dt.date
            .max()
        )

        st.markdown(
            f"### 📊 Cumulative Performance of 2-Hour Ahead Forecast "
            f"({cumulative_2hr_start} to {cumulative_2hr_end})"
        )

        actual_cum_2hr = cumulative_2hr_df["Actual_GHI"]
        gfs_cum_2hr = cumulative_2hr_df["GFS_GHI"]
        daily_cum_2hr = cumulative_2hr_df[
            "Daily_Forecast_GHI"
        ]
        forecast_cum_2hr = cumulative_2hr_df[
            "Two_Hour_Ahead_Forecast"
        ]

        # =====================================================
        # MAPE
        # =====================================================

        cumulative_mape_gfs = (
            (
                (actual_cum_2hr - gfs_cum_2hr).abs()
                / actual_cum_2hr
            ).mean()
            * 100
        )

        cumulative_mape_daily = (
            (
                (actual_cum_2hr - daily_cum_2hr).abs()
                / actual_cum_2hr
            ).mean()
            * 100
        )

        cumulative_mape_2hr = (
            (
                (actual_cum_2hr - forecast_cum_2hr).abs()
                / actual_cum_2hr
            ).mean()
            * 100
        )

        # =====================================================
        # MAE
        # =====================================================

        cumulative_mae_gfs = (
            actual_cum_2hr - gfs_cum_2hr
        ).abs().mean()

        cumulative_mae_daily = (
            actual_cum_2hr - daily_cum_2hr
        ).abs().mean()

        cumulative_mae_2hr = (
            actual_cum_2hr - forecast_cum_2hr
        ).abs().mean()

        # =====================================================
        # RMSE
        # =====================================================

        cumulative_rmse_gfs = np.sqrt(
            ((actual_cum_2hr - gfs_cum_2hr) ** 2).mean()
        )

        cumulative_rmse_daily = np.sqrt(
            ((actual_cum_2hr - daily_cum_2hr) ** 2).mean()
        )

        cumulative_rmse_2hr = np.sqrt(
            ((actual_cum_2hr - forecast_cum_2hr) ** 2).mean()
        )

        comparison_labels = [
            "Before\n(GFS)",
            "After\n(Daily)",
            "After\n(2-Hour)"
        ]

        comparison_colors = [
            GFS_COLOR,
            DAILY_FORECAST_COLOR,
            TWO_HOUR_COLOR
        ]

        twohr_metric_col1, twohr_metric_col2, twohr_metric_col3 = (
            st.columns(3)
        )

        # =====================================================
        # CUMULATIVE 2-HOUR MAPE
        # =====================================================

        with twohr_metric_col1:
            with st.container(border=True):

                fig_2hr_mape = go.Figure()

                fig_2hr_mape.add_trace(go.Bar(
                    x=comparison_labels,
                    y=[
                        cumulative_mape_gfs,
                        cumulative_mape_daily,
                        cumulative_mape_2hr
                    ],
                    text=[
                        f"{cumulative_mape_gfs:.2f}",
                        f"{cumulative_mape_daily:.2f}",
                        f"{cumulative_mape_2hr:.2f}"
                    ],
                    textposition="auto",
                    marker_color=comparison_colors
                ))

                fig_2hr_mape.update_layout(
                    title="MAPE",
                    xaxis_title="Forecast Stage",
                    yaxis_title="MAPE (%)",
                    height=350,
                    margin=dict(
                        l=35,
                        r=20,
                        t=55,
                        b=40
                    ),
                    showlegend=False
                )

                st.plotly_chart(
                    fig_2hr_mape,
                    use_container_width=True,
                    key="cumulative_2hr_mape_chart"
                )

        # =====================================================
        # CUMULATIVE 2-HOUR MAE
        # =====================================================

        with twohr_metric_col2:
            with st.container(border=True):

                fig_2hr_mae = go.Figure()

                fig_2hr_mae.add_trace(go.Bar(
                    x=comparison_labels,
                    y=[
                        cumulative_mae_gfs,
                        cumulative_mae_daily,
                        cumulative_mae_2hr
                    ],
                    text=[
                        f"{cumulative_mae_gfs:.2f}",
                        f"{cumulative_mae_daily:.2f}",
                        f"{cumulative_mae_2hr:.2f}"
                    ],
                    textposition="auto",
                    marker_color=comparison_colors
                ))

                fig_2hr_mae.update_layout(
                    title="MAE",
                    xaxis_title="Forecast Stage",
                    yaxis_title="MAE",
                    height=350,
                    margin=dict(
                        l=35,
                        r=20,
                        t=55,
                        b=40
                    ),
                    showlegend=False
                )

                st.plotly_chart(
                    fig_2hr_mae,
                    use_container_width=True,
                    key="cumulative_2hr_mae_chart"
                )

        # =====================================================
        # CUMULATIVE 2-HOUR RMSE
        # =====================================================

        with twohr_metric_col3:
            with st.container(border=True):

                fig_2hr_rmse = go.Figure()

                fig_2hr_rmse.add_trace(go.Bar(
                    x=comparison_labels,
                    y=[
                        cumulative_rmse_gfs,
                        cumulative_rmse_daily,
                        cumulative_rmse_2hr
                    ],
                    text=[
                        f"{cumulative_rmse_gfs:.2f}",
                        f"{cumulative_rmse_daily:.2f}",
                        f"{cumulative_rmse_2hr:.2f}"
                    ],
                    textposition="auto",
                    marker_color=comparison_colors
                ))

                fig_2hr_rmse.update_layout(
                    title="RMSE",
                    xaxis_title="Forecast Stage",
                    yaxis_title="RMSE",
                    height=350,
                    margin=dict(
                        l=35,
                        r=20,
                        t=55,
                        b=40
                    ),
                    showlegend=False
                )

                st.plotly_chart(
                    fig_2hr_rmse,
                    use_container_width=True,
                    key="cumulative_2hr_rmse_chart"
                )

    else:
        st.markdown(
            f"### 📊 Cumulative Performance of 2-Hour Ahead Forecast "
            f"(Through {previous_day})"
        )

        st.warning(
            "No valid 2-hour-ahead forecast data is available "
            "from the beginning of the dataset through the previous day."
        )

    # =====================================================
    # OVERALL FULL-DATA PERFORMANCE METRICS
    # =====================================================

    overall_df = df.dropna(
        subset=[
            "Actual_GHI",
            "GFS_GHI",
            "Daily_Forecast_GHI"
        ]
    ).copy()

    overall_df["hour"] = (
        overall_df["valid_time_ist"].dt.hour
        + overall_df["valid_time_ist"].dt.minute / 60
    )

    overall_df = overall_df[
        (overall_df["hour"] >= 6.5)
        & (overall_df["hour"] <= 17.5)
        & (overall_df["Actual_GHI"] > 50)
    ].copy()

    # =====================================================
    # METRIC CARD FUNCTION
    # =====================================================

    def show_metric_card(title, metric_rows):
        """
        metric_rows:
        [
            (label, displayed_value, value_color, font_size),
            ...
        ]
        """

        with st.container(border=True):

            st.markdown(
                f"""
                <h3 style="
                    color:#FF3B30;
                    font-size:1.45rem;
                    margin-top:0;
                    margin-bottom:14px;
                ">
                    {title}
                </h3>
                """,
                unsafe_allow_html=True
            )

            for row_number, row in enumerate(metric_rows):

                label = row[0]
                displayed_value = row[1]
                value_color = row[2]
                font_size = row[3]

                metric_html = (
                    f'<div style="'
                    f'padding-top:12px;'
                    f'padding-bottom:12px;">'

                    f'<div style="'
                    f'font-size:0.88rem;'
                    f'font-weight:600;'
                    f'margin-bottom:5px;'
                    f'color:inherit;">'
                    f'{label}'
                    f'</div>'

                    f'<div style="'
                    f'color:{value_color};'
                    f'font-size:{font_size};'
                    f'font-weight:750;'
                    f'line-height:1.15;">'
                    f'{displayed_value}'
                    f'</div>'

                    f'</div>'
                )

                st.markdown(
                    metric_html,
                    unsafe_allow_html=True
                )

    if not overall_df.empty:

        # =====================================================
        # DAILY FORECAST METRICS
        # =====================================================

        daily_start_date = (
            overall_df["valid_time_ist"].dt.date.min()
        )

        daily_end_date = (
            overall_df["valid_time_ist"].dt.date.max()
        )

        actual_all = overall_df["Actual_GHI"]
        gfs_all = overall_df["GFS_GHI"]
        daily_all = overall_df["Daily_Forecast_GHI"]

        overall_mape_before = (
            ((actual_all - gfs_all).abs() / actual_all).mean()
            * 100
        )

        overall_mape_after = (
            ((actual_all - daily_all).abs() / actual_all).mean()
            * 100
        )

        overall_mae_before = (
            (actual_all - gfs_all).abs().mean()
        )

        overall_mae_after = (
            (actual_all - daily_all).abs().mean()
        )

        overall_rmse_before = np.sqrt(
            ((actual_all - gfs_all) ** 2).mean()
        )

        overall_rmse_after = np.sqrt(
            ((actual_all - daily_all) ** 2).mean()
        )

        st.markdown("## 📌 Overall Forecast Performance")

        left_summary, right_summary = st.columns(2)

        # =====================================================
        # LEFT SIDE: DAILY FORECAST
        # =====================================================

        with left_summary:

            with st.container(border=True):

                st.markdown(
                    f"""
                    <div style="
                        font-size:1.5rem;
                        font-weight:700;
                        line-height:1.25;
                        white-space:nowrap;
                        margin-bottom:8px;
                    ">
                        📈 Daily Forecast
                        ({daily_start_date} to {daily_end_date})
                    </div>
                    """,
                    unsafe_allow_html=True
                )

                st.markdown(
                    """
                    <div style="
                        font-size:0.92rem;
                        color:inherit;
                        margin-bottom:2px;
                    ">
                        Comparison of Actual GHI, GFS and Daily Forecast GHI
                    </div>
                    """,
                    unsafe_allow_html=True
                )

            k1, k2, k3 = st.columns(3)

            # ---------------- MAPE ----------------
            with k1:
                show_metric_card(
                    "🎯 MAPE",
                    [
                        (
                            "Actual vs GFS",
                            f"{overall_mape_before:.2f}%",
                            GFS_COLOR,
                            "1.40rem"
                        ),
                        (
                            "Actual vs Daily Forecast",
                            f"{overall_mape_after:.2f}%",
                            DAILY_FORECAST_COLOR,
                            "2.15rem"
                        )
                    ]
                )

            # ---------------- MAE ----------------
            with k2:
                show_metric_card(
                    "📊 MAE",
                    [
                        (
                            "Actual vs GFS",
                            f"{overall_mae_before:.2f}",
                            GFS_COLOR,
                            "1.40rem"
                        ),
                        (
                            "Actual vs Daily Forecast",
                            f"{overall_mae_after:.2f}",
                            DAILY_FORECAST_COLOR,
                            "2.15rem"
                        )
                    ]
                )

            # ---------------- RMSE ----------------
            with k3:
                show_metric_card(
                    "〽️ RMSE",
                    [
                        (
                            "Actual vs GFS",
                            f"{overall_rmse_before:.2f}",
                            GFS_COLOR,
                            "1.40rem"
                        ),
                        (
                            "Actual vs Daily Forecast",
                            f"{overall_rmse_after:.2f}",
                            DAILY_FORECAST_COLOR,
                            "2.15rem"
                        )
                    ]
                )

        # =====================================================
        # RIGHT SIDE: 2-HOUR-AHEAD FORECAST
        # =====================================================

        with right_summary:

            two_hour_metrics_df = overall_df.dropna(
                subset=["Two_Hour_Ahead_Forecast"]
            ).copy()

            if not two_hour_metrics_df.empty:

                twohr_start_date = (
                    two_hour_metrics_df[
                        "valid_time_ist"
                    ].dt.date.min()
                )

                twohr_end_date = (
                    two_hour_metrics_df[
                        "valid_time_ist"
                    ].dt.date.max()
                )

                actual_2hr = (
                    two_hour_metrics_df["Actual_GHI"]
                )

                gfs_2hr = (
                    two_hour_metrics_df["GFS_GHI"]
                )

                daily_2hr = (
                    two_hour_metrics_df["Daily_Forecast_GHI"]
                )

                forecast_2hr = (
                    two_hour_metrics_df[
                        "Two_Hour_Ahead_Forecast"
                    ]
                )

                # =====================================================
                # MAPE
                # =====================================================

                mape_gfs = (
                    (
                        (actual_2hr - gfs_2hr).abs()
                        / actual_2hr
                    ).mean()
                    * 100
                )

                mape_daily = (
                    (
                        (actual_2hr - daily_2hr).abs()
                        / actual_2hr
                    ).mean()
                    * 100
                )

                mape_2hr = (
                    (
                        (actual_2hr - forecast_2hr).abs()
                        / actual_2hr
                    ).mean()
                    * 100
                )

                # =====================================================
                # MAE
                # =====================================================

                mae_gfs = (
                    (actual_2hr - gfs_2hr).abs().mean()
                )

                mae_daily = (
                    (actual_2hr - daily_2hr).abs().mean()
                )

                mae_2hr = (
                    (actual_2hr - forecast_2hr).abs().mean()
                )

                # =====================================================
                # RMSE
                # =====================================================

                rmse_gfs = np.sqrt(
                    ((actual_2hr - gfs_2hr) ** 2).mean()
                )

                rmse_daily = np.sqrt(
                    ((actual_2hr - daily_2hr) ** 2).mean()
                )

                rmse_2hr = np.sqrt(
                    ((actual_2hr - forecast_2hr) ** 2).mean()
                )

                with st.container(border=True):

                    st.markdown(
                        f"""
                        <div style="
                            font-size:1.5rem;
                            font-weight:700;
                            line-height:1.25;
                            white-space:nowrap;
                            margin-bottom:8px;
                        ">
                            🕒 2-Hour Ahead Forecast
                            ({twohr_start_date} to {twohr_end_date})
                        </div>
                        """,
                        unsafe_allow_html=True
                    )

                    st.markdown(
                        """
                        <div style="
                            font-size:0.92rem;
                            color:inherit;
                            margin-bottom:2px;
                        ">
                            Calculated only for rows where
                            2-Hour Ahead Forecast is available
                        </div>
                        """,
                        unsafe_allow_html=True
                    )

                h1, h2, h3 = st.columns(3)

                # ---------------- MAPE ----------------
                with h1:
                    show_metric_card(
                        "🎯 MAPE",
                        [
                            (
                                "Actual vs GFS",
                                f"{mape_gfs:.2f}%",
                                GFS_COLOR,
                                "1.30rem"
                            ),
                            (
                                "Actual vs Daily Forecast",
                                f"{mape_daily:.2f}%",
                                DAILY_FORECAST_COLOR,
                                "1.70rem"
                            ),
                            (
                                "Actual vs 2-Hour Ahead",
                                f"{mape_2hr:.2f}%",
                                TWO_HOUR_COLOR,
                                "2.15rem"
                            )
                        ]
                    )

                # ---------------- MAE ----------------
                with h2:
                    show_metric_card(
                        "📊 MAE",
                        [
                            (
                                "Actual vs GFS",
                                f"{mae_gfs:.2f}",
                                GFS_COLOR,
                                "1.30rem"
                            ),
                            (
                                "Actual vs Daily Forecast",
                                f"{mae_daily:.2f}",
                                DAILY_FORECAST_COLOR,
                                "1.70rem"
                            ),
                            (
                                "Actual vs 2-Hour Ahead",
                                f"{mae_2hr:.2f}",
                                TWO_HOUR_COLOR,
                                "2.15rem"
                            )
                        ]
                    )

                # ---------------- RMSE ----------------
                with h3:
                    show_metric_card(
                        "〽️ RMSE",
                        [
                            (
                                "Actual vs GFS",
                                f"{rmse_gfs:.2f}",
                                GFS_COLOR,
                                "1.30rem"
                            ),
                            (
                                "Actual vs Daily Forecast",
                                f"{rmse_daily:.2f}",
                                DAILY_FORECAST_COLOR,
                                "1.70rem"
                            ),
                            (
                                "Actual vs 2-Hour Ahead",
                                f"{rmse_2hr:.2f}",
                                TWO_HOUR_COLOR,
                                "2.15rem"
                            )
                        ]
                    )

            else:
                with st.container(border=True):
                    st.markdown(
                        "### 🕒 2-Hour Ahead Forecast"
                    )

                    st.warning(
                        "No valid 2-hour-ahead forecast data is "
                        "available for overall performance."
                    )

    else:
        st.warning(
            "Not enough valid data to calculate "
            "overall forecast performance."
        )
# =====================================================
# MONTHLY OVERALL PERFORMANCE — DAILY FORECAST MAE
# =====================================================

monthly_mae_df = df.dropna(
    subset=[
        "valid_time_ist",
        "Actual_GHI",
        "Daily_Forecast_GHI"
    ]
).copy()

monthly_mae_df["hour"] = (
    monthly_mae_df["valid_time_ist"].dt.hour
    + monthly_mae_df["valid_time_ist"].dt.minute / 60
)

# Use the same evaluation condition as the other metrics
monthly_mae_df = monthly_mae_df[
    (monthly_mae_df["hour"] >= 6.5)
    & (monthly_mae_df["hour"] <= 17.5)
    & (monthly_mae_df["Actual_GHI"] > 50)
].copy()

if not monthly_mae_df.empty:

    monthly_mae_df["year_month"] = (
        monthly_mae_df["valid_time_ist"].dt.to_period("M")
    )

    monthly_mae_df["absolute_error"] = (
        monthly_mae_df["Actual_GHI"]
        - monthly_mae_df["Daily_Forecast_GHI"]
    ).abs()

    monthly_performance = (
        monthly_mae_df
        .groupby("year_month", as_index=False)["absolute_error"]
        .mean()
        .rename(columns={"absolute_error": "Monthly_MAE"})
    )

    monthly_performance["Month"] = (
        monthly_performance["year_month"]
        .dt.to_timestamp()
        .dt.strftime("%b %Y")
    )

    monthly_performance = monthly_performance.sort_values(
        "year_month"
    ).reset_index(drop=True)

    monthly_start = (
        monthly_mae_df["valid_time_ist"].dt.date.min()
    )

    monthly_end = (
        monthly_mae_df["valid_time_ist"].dt.date.max()
    )

    st.markdown(
        f"## 📅 Monthly Daily Forecast Performance "
        f"({monthly_start} to {monthly_end})"
    )

    with st.container(border=True):

        st.markdown(
            "### Monthly MAE of Daily Forecast GHI"
        )

        # =====================================================
        # BUILD 3D BARS USING MESH3D
        # =====================================================

        fig_monthly_mae = go.Figure()

        bar_width = 0.64
        bar_depth = 0.65

        for i, row in monthly_performance.iterrows():

            mae_value = float(row["Monthly_MAE"])

            # Cuboid boundaries
            x0 = i - bar_width / 2
            x1 = i + bar_width / 2

            y0 = -bar_depth / 2
            y1 = bar_depth / 2

            z0 = 0
            z1 = mae_value

            # Eight vertices of one cuboid
            x_vertices = [
                x0, x1, x1, x0,
                x0, x1, x1, x0
            ]

            y_vertices = [
                y0, y0, y1, y1,
                y0, y0, y1, y1
            ]

            z_vertices = [
                z0, z0, z0, z0,
                z1, z1, z1, z1
            ]

            # Triangular faces of the cuboid
            fig_monthly_mae.add_trace(go.Mesh3d(
                x=x_vertices,
                y=y_vertices,
                z=z_vertices,

                i=[
                    0, 0, 4, 4,
                    0, 1, 2, 3,
                    0, 1, 2, 3
                ],

                j=[
                    1, 2, 5, 6,
                    1, 2, 3, 0,
                    4, 5, 6, 7
                ],

                k=[
                    2, 3, 6, 7,
                    5, 6, 7, 4,
                    5, 6, 7, 4
                ],

                color=DAILY_FORECAST_COLOR,
                opacity=0.92,
                flatshading=True,

                hovertemplate=(
                    f"<b>{row['Month']}</b><br>"
                    f"Monthly MAE: {mae_value:.2f}"
                    "<extra></extra>"
                ),

                showlegend=False
            ))

            # Value label above each bar
            fig_monthly_mae.add_trace(go.Scatter3d(
                x=[i],
                y=[0],
                z=[mae_value + max(
                    monthly_performance["Monthly_MAE"].max() * 0.03,
                    2
                )],
                mode="text",
                text=[f"{mae_value:.2f}"],
                textfont=dict(size=11),
                hoverinfo="skip",
                showlegend=False
            ))

        fig_monthly_mae.update_layout(
            height=650,
            margin=dict(
                l=10,
                r=10,
                t=25,
                b=10
            ),

            scene=dict(
                xaxis=dict(
                    title="Month",
                    tickmode="array",
                    tickvals=list(
                        range(len(monthly_performance))
                    ),
                    ticktext=monthly_performance[
                        "Month"
                    ].tolist(),
                    tickangle=-45
                ),

                yaxis=dict(
                    title="",
                    showticklabels=False,
                    showgrid=False,
                    zeroline=False,
                    range=[-1.2, 1.2]
                ),

                zaxis=dict(
                    title="MAE",
                    rangemode="tozero"
                ),

                camera=dict(
                    eye=dict(
                        x=1.55,
                        y=-1.65,
                        z=1.15
                    )
                ),

                aspectmode="manual",

                aspectratio=dict(
                    x=max(
                        len(monthly_performance) / 7,
                        1.8
                    ),
                    y=0.7,
                    z=1.1
                )
            )
        )

        st.plotly_chart(
            fig_monthly_mae,
            use_container_width=True,
            key="monthly_daily_forecast_mae_3d"
        )

else:
    st.warning(
        "Not enough valid data is available to calculate "
        "monthly Daily Forecast MAE."
    )
